version: '3'

volumes:
  postgres_data:
  pgadmin_data:
      driver: local
services:
  postgres:
      image: postgres
      restart: always
      volumes:
        - postgres_data:/var/lib/postgresql/data
        - $PWD/postgres.conf:/etc/postgresql/postgresql.conf
      command: postgres -c config_file=/etc/postgresql/postgresql.conf
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
        PGDATA: /data/postgres
        ALLOW_IP_RANGE: 0.0.0.0/0
      ports:
        - "${POSTGRES_PORT:-5432}:5432"
      networks:
        - devnet
  pgadmin:
      container_name: pgadmin_container
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      volumes:
        - pgadmin_data:/root/.pgadmin
      ports:
        - "${PGADMIN_PORT:-5050}:80"
      networks:
        - devnet
      restart: unless-stopped
      depends_on:
        - postgres
  keycloak:
      image: jboss/keycloak
      restart: always
      environment:
        PROXY_ADDRESS_FORWARDING: 'true'
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
        - 8080:8080
      volumes:
        - ./keycloak/configuration/standalone.xml:/opt/jboss/keycloak/standalone/configuration/standalone.xml
      networks:
        - devnet
      depends_on:
        - postgres
  networks:
    devnet:
      driver: bridge



